command_timeout	= 1200

[character]
error_symbol = "[❯](bold #ff0000)"

[terraform]
format = "[$symbol$version]($style) "

[aws]
format = 'on [$symbol($profile )(\[$duration\])]($style)'

[gcloud]
disabled = true


