name: benchmark

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

concurrency: benchmark

jobs:
  benchmark:
    runs-on: macos-latest
    timeout-minutes: 15
    env:
      DOTFILES_HOME: /Users/runner/work/dotfiles/dotfiles/mac
      ZDOTDIR: /Users/runner/work/dotfiles/dotfiles/mac/zsh
      TERM_PROGRAM: Apple_Terminal
      XDG_CONFIG_HOME: /Users/runner/work/dotfiles/dotfiles/mac/zsh

    steps:
    - uses: actions/checkout@v2

    - name: link zshrc
      run: ln -sf $ZDOTDIR/.zshrc ~/.zshrc && echo $ZDOTDIR

    - name: Remove .gitconfig
      run: rm ~/.gitconfig

    - name: Configure Homebrew cache
      uses: actions/cache@v2
      with:
        path: |
          ~/Library/Caches/Homebrew/
        key: brew-${{ hashFiles('.github/workflows/Brewfile') }}
        restore-keys: brew-

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@94e3bec1ef6f44b49185f96a83e716756fd7b088

    - name: Install Formula
      env:
        HOMEBREW_NO_INSTALL_UPGRADE: 1
        HOMEBREW_NO_INSTALL_CLEANUP: 1
      run: |
        brew bundle --verbose --no-lock --file=.github/workflows/Brewfile

    - name: Run benchmark
      run: |
        echo $ZDOTDIR
        ./.github/workflows/benchmark.sh > result.json

    - name: Upload benchmark
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: customSmallerIsBetter
        output-file-path: result.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        comment-on-alert: true
        fail-on-alert: false
        alert-threshold: '150%'
        alert-comment-cc-users: '@korosuke613'
